---
- name: Update all packages
  yum: name=* state=latest

- name: Install EPEL repository
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: Install Remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: Install python module for Copy module
  yum: name=libselinux-python
