---
- name: Install PHP
  yum: enablerepo=remi,remi-php55 name={{ item }}
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-opcache

- name: Copy php.ini file
  copy: src=php.ini dest=/etc/php.ini
  notify: httpd restart
