---
- hosts: all
  sudo: yes
  roles:
    - { role: common, tags: common  }
    - { role: apache, tags: apache  }
    - { role: php, tags: php }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: wp-cli, tags: wp-cli }
